import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Nav from '@/components/nav'
import { Inter } from 'next/font/google'
import styles from './index.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const res = await axios({
    method: 'get',
    url: 'https://6702f219-422b-4b39-8c17-0eff2c60daa8.mock.pstmn.io/api/v1/social/token?sym=FUT',
    headers: {
      // 'Accept': 'application/vnd.github.v3+json'
    },
    params: {
      client_id: process.env.GITHUB_CLIENT_ID,
      client_secret: process.env.GITHUB_CLIENT_SECRET
    }
  })

  console.log(res);
  debugger

  return {
    props: {
      datum: res.data
    }
  }
}

export default function App(props: { datum: any }) {

  const { datum } = props;

  console.log('datum', datum);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{ "color": styles.primaryColor }}>
        <Nav />
        <div >
          <p>
            Get started by editing&nbsp;
            <code>pages/demo.tsx</code>
          </p>
        </div>
      </main>
    </>
  )
}
